package br.com.gustavo.streamdeck.network

import java.util.UUID

/** Device identity generated by the app; it is never entered or displayed during pairing. */
object ClientIdentity {
    fun generate(): String = "android-${UUID.randomUUID()}"
}
